### ISSUE TITLE
Can support to get found links??

### ISSUE THREAD

**Issue by AkoWu101** [apradanas/simple-linkable-text#1]
Any public method to get found links in the future?

**Comment by apradanas** [comment]
Hello @KingWu 

It's included in ![v1.0.3](https://github.com/apradanas/simple-linkable-text/tree/v1.0.3).
You can use `List<Link> foundLinks = editText.getFoundLinks()` or `List<Link> foundLinks = textView.getFoundLinks()`. You can check ![sample](https://github.com/apradanas/simple-linkable-text/blob/master/sample/src/main/java/com/apradanas/simplelinkabletextsample/MainActivity.java) as well.

Thank you for your feedback.
